### ISSUE TITLE
Hello Mr. Sastra Nababan

### ISSUE THREAD

**Issue by adityosnento** [SastraNababan/bicara-hook#1]
Thank you for your video, it's very helpfully.. but i got some issue when i start the project. like this :

**TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined**

**Comment by SastraNababan** [comment]
Hi @adityosnento 
Thanks for report this
This issue related to [this](https://github.com/facebook/create-react-app/issues/8499)

I've upgraded all packages. Here's the next step you can do :
-  `git pull` this repo 
- remove your node_modules
- run setup `npm run setup` 

Good Luck!
